spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabank?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
      name: atm-data-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
