eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: atm-zuul-servuce
zuul:
  routes:
#    api-a:
#      path: /api-data/**
#      serviceId: atm-data-service
    api-b:
      path: /api-view/**
      serviceId: atm-view-service
